name: Build Electron App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        arch: [x86]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build Electron app
      run: npm run build

    - name: Package Electron app
      run: |
        npm install electron-packager -g
        electron-packager . excel-app --platform=win32 --arch=${{ matrix.arch }} --out=release-build --overwrite

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: electron-app
        path: release-build
