name: Build Electron App

on:
  push:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest

    strategy:
      matrix:
        arch: [x64]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Package Electron app
      run: npm run build:win

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: electron-app
        path: release-build
  
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build Electron app for macOS
        run: npm run build:mac

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: electron-app-macos
          path: release-build
